name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  import-simple:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - name: Torch-MLIR import
        run: pixi run python examples/${{ matrix.example }}
    strategy:
      matrix:
        kernel: [nnmodule, torchvision]
