name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-example:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          environments: ${{ matrix.env }}
      - name: Import example
        run: pixi run -e ${{ matrix.env }} python examples/${{ matrix.example }}.py
    strategy:
      matrix:
        include:
          - { example: nnmodule, env: default }
          - { example: torchvision_resnet, env: default }
          - { example: transformers_whispersmall, env: default }
          - { example: transformers_berttiny, env: default }
          - { example: transformers_tinystories, env: default }
          - { example: mlperftiny_ad01_float, env: tflite }
          - { example: mlperftiny_ad01_int8, env: tflite }
          - { example: mlperftiny_kws_float, env: tflite }
          - { example: mlperftiny_kws_int8, env: tflite }
          - { example: mlperftiny_resnet_float, env: tflite }
          - { example: mlperftiny_resnet_int8, env: tflite }
          - { example: mlperftiny_vww_float, env: tflite }
          - { example: mlperftiny_vww_int8, env: tflite }
